apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: task-app
  labels:
    app: frontend-service
spec:
  ports:
  - port: 8002
    targetPort: 8002
  selector:
    app: frontend-service
  type: LoadBalancer  # Exposed externally for user access